-- schema.sql
USE ESI;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  discord VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  characterId VARCHAR(255) NOT NULL,
  refreshToken TEXT NOT NULL,
  expire INT NOT NULL,
  addDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (characterId),
  INDEX idx_discord (discord)
);

CREATE TABLE IF NOT EXISTS dmSubscribe (
  id INT AUTO_INCREMENT PRIMARY KEY,
  discord_id VARCHAR(255) NOT NULL UNIQUE,
  sub BOOLEAN NOT NULL
);

CREATE DATABASE IF NOT EXISTS c5Ratting;
USE c5Ratting;

CREATE TABLE IF NOT EXISTS stats (
  id INT AUTO_INCREMENT PRIMARY KEY,
  totalBlueLoot FLOAT NOT NULL,
  blueLootPerHour FLOAT NOT NULL,
  totalSalvage FLOAT NOT NULL,
  blueLootTax FLOAT NOT NULL,
  SalvageTax FLOAT NOT NULL,
  totalTax FLOAT NOT NULL,
  duration INT NOT NULL,
  composition VARCHAR(255) NOT NULL,
  rattingdate DATE NOT NULL
);
