services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: MANAISCUTE
      MYSQL_DATABASE: ESI
      MYSQL_USER: admin
      MYSQL_PASSWORD: MANAISCUTE
    ports:
      - "3306:3306"   # ← 추가
