version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cat4u-mysql
    environment:
      MYSQL_ROOT_PASSWORD: MANAISCUTE
      MYSQL_DATABASE: ESI
      MYSQL_USER: admin
      MYSQL_PASSWORD: MANAISCUTE
    expose:
      - "3306"
    networks:
      - internal_net
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  internal_net:
    driver: bridge

volumes:
  mysql_data:
