name: Deploy to AWS Server

on:
  push:
    branches:
      - dev # dev 브랜치로 푸시나 merge될 때만 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "서버 업데이트가 감지되었습니다 서버를 재시작 합니다!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Deploy to AWS Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /Cat4U  # 프로젝트 위치로 이동
            git pull origin dev       # dev 브랜치에서 최신 코드 가져오기
            npm install               # 필요한 패키지 설치
            pm2 restart your-app      # PM2로 앱 재시작
          EOF
